# 基础配置
server:
  port: 8082

spring:
  application:
    name: enrollment-service
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ms_enrollment_user
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# 服务间通信配置
catalog-service:
  url: http://localhost:8081